// This is a recreation of Figure 1 from Frangi et al. 1998
// "Multiscale vessel enhancement filtering"
//
// Generated by Claude Opus 4.7 with modifications


// https://typst.app/universe/package/cetz/
// https://github.com/cetz-package/cetz-plot

#import "@preview/cetz:0.5.2"
#import "@preview/cetz-plot:0.1.3": plot, chart

#figure(
  grid(
    columns: (1fr, 1fr),
    column-gutter: 1em,
    align: horizon,

    // ============================================================
    // LEFT PANEL: Second derivative of a Gaussian
    // ============================================================
    cetz.canvas({
      import cetz.draw: *

      plot.plot(
        size: (5, 4),
        x-tick-step: 2,
        y-tick-step: 0.4,
        x-min: -5, x-max: 5,
        y-min: -1.1, y-max: 0.6,
        x-label: $x$,
        y-label: $G''_sigma (x)$,
        axis-style: "school-book",
        {
          // Second derivative of a Gaussian with sigma=1:
          //   G''(x) = (x^2 - 1) / sqrt(2*pi) * exp(-x^2 / 2)
          plot.add(
            domain: (-5, 5),
            samples: 200,
            style: (stroke: black + 1pt),
            x => (calc.pow(x, 2) - 1)
                 / calc.sqrt(2 * calc.pi)
                 * calc.exp(-calc.pow(x, 2) / 2),
          )

          // Shade the curve (under-curve fill); cetz-plot supports
          // fill via the `fill` style on plot.add. If your version
          // does not, remove this second add() call — the curve
          // alone is sufficient for the figure to read clearly.
          plot.add(
            domain: (-5, 5),
            samples: 200,
            style: (stroke: none, fill: gray.transparentize(60%)),
            fill: true,
            x => (calc.pow(x, 2) - 1)
                 / calc.sqrt(2 * calc.pi)
                 * calc.exp(-calc.pow(x, 2) / 2),
          )
        },
      )
    }),

    // ============================================================
    // RIGHT PANEL: Cylinder with eigenvectors and curvature ellipsoid
    // ============================================================
    cetz.canvas({
      import cetz.draw: *

      // ----- Geometry parameters -----
      // Cylinder
      let cyl-half-len = 3.0
      let cyl-radius = 1.0
      let cap-flatness = 0.35

      // Second-order ellipsoid: PROLATE, long axis along λ1.
      // Tune the ratio between long and short axes to control
      // how dramatically tube-like the ellipsoid appears.
      let ell-long  = 1.4    // semi-axis along λ1 (cylinder axis)
      let ell-short = 0.55   // semi-axis along λ2 (vertical)
      let ell-depth = 0.55   // semi-axis along λ3 (into page)
      // Foreshortening factor for "into the page" axis: how much
      // the depth dimension is squashed when projected to 2D.
      let depth-squash = 0.35

      // ----- Cylinder body -----
      circle(
        (cyl-half-len, 0),
        radius: (cap-flatness, cyl-radius),
        stroke: black + 0.8pt,
      )
      circle(
        (-cyl-half-len, 0),
        radius: (cap-flatness, cyl-radius),
        stroke: black + 0.8pt,
      )
      line(
        (-cyl-half-len, cyl-radius),
        (cyl-half-len, cyl-radius),
        stroke: black + 0.8pt,
      )
      line(
        (-cyl-half-len, -cyl-radius),
        (cyl-half-len, -cyl-radius),
        stroke: black + 0.8pt,
      )

      // ----- Second-order ellipsoid (prolate, dotted wireframe) -----
      //
      // Element 1: SILHOUETTE — the outer outline of the ellipsoid as
      // seen from the viewer's angle. Long axis along λ1 (horizontal),
      // short axis along λ2 (vertical). This is the dominant visual
      // shape that makes the ellipsoid look tube-like.
      circle(
        (0, 0),
        radius: (ell-long, ell-short),
        stroke: (paint: black, dash: "dotted", thickness: 0.7pt),
      )

      // Element 2: CROSS-SECTION at the centre, in the (λ2, λ3) plane.
      // Drawn as a small vertical ellipse: tall along λ2, narrow along
      // the foreshortened λ3 (into-page) direction.
      // This element makes the shape read as 3D rather than a flat oval.
      circle(
        (0, 0),
        radius: (ell-depth * depth-squash, ell-short),
        stroke: (paint: black, dash: "dotted", thickness: 0.7pt),
      )

      // Element 3 (optional but recommended): the "equator" of the
      // ellipsoid — a horizontal ellipse in the (λ1, λ3) plane,
      // strongly foreshortened. This creates the wireframe-ball
      // appearance and matches the original figure's three-curve
      // construction. Commented out by default; uncomment if your
      // first render of the ellipsoid looks too flat.
      //
      // circle(
      //   (0, 0),
      //   radius: (ell-long, ell-depth * depth-squash),
      //   stroke: (paint: black, dash: "dotted", thickness: 0.7pt),
      // )

      // ----- Eigenvector axes (dashed, through the centre) -----
      // λ1: along the cylinder axis (horizontal).
      let lam1-len = cyl-half-len + 0.9
      line(
        (-lam1-len, 0),
        (lam1-len, 0),
        stroke: (paint: black, dash: "dashed", thickness: 0.6pt),
      )
      content(
        (lam1-len + 0.15, 0),
        anchor: "west",
        $lambda_1$,
      )

      // λ2: vertical, perpendicular to cylinder axis, in image plane.
      let lam2-len = cyl-radius + 0.9
      line(
        (0, -lam2-len),
        (0, lam2-len),
        stroke: (paint: black, dash: "dashed", thickness: 0.6pt),
      )
      content(
        (0, lam2-len + 0.15),
        anchor: "south",
        $lambda_2$,
      )

      // λ3: into the page, drawn as a foreshortened diagonal to
      // suggest depth.
      let lam3-dx = 0.9
      let lam3-dy = 0.55
      line(
        (-lam3-dx, -lam3-dy),
        (lam3-dx, lam3-dy),
        stroke: (paint: black, dash: "dashed", thickness: 0.6pt),
      )
      content(
        (lam3-dx + 0.1, lam3-dy + 0.05),
        anchor: "south-west",
        $lambda_3$,
      )
    }),
  ),
  caption: [
    The Frangi vesselness filter: Figure adapted from @frangi_og_paper.
    
    *Left:* The second-order derivative of a Gaussian kernel $G''_sigma$ probes inside-versus-outside contrast over the spatial range $(-sigma, sigma)$; here $sigma = 1$. Convolving an image with this kernel measures for each point how strongly intensity curves over the scale _sigma_: high response means a detected peak or valley of width comparable to _sigma_ - "matching" vessels.
    
    *Right:* At each voxel, the eigen-decomposition of the Hessian matrix yields three principal directions of curvature $lambda_1, lambda_2, lambda_3$. For a tubular structure, the eigenvalue along the vessel axis ($lambda_1$) has small magnitude (intensity is roughly constant along the vessel) while the two perpendicular eigenvalues ($lambda_2, lambda_3$) have large magnitude and the same sign (reflecting the drop in intensity in either direction perpendicular to the vessel) this constitutes the geometric signature Frangi's filter exploits and are combined to form the Frangi vesselness score.
  ],
) <fig:frangi-hessian>