// Plot grey-value gradient profiles produced by extract_gradients.py.
// Generated by Claude Opus 4.7 with modifications

// Relevant: https://raw.githubusercontent.com/cetz-package/cetz-plot/refs/tags/v0.1.0/manual.pdf

// https://typst.app/universe/package/cetz/
// https://github.com/cetz-package/cetz-plot

#import "@preview/cetz:0.5.2"
#import "@preview/cetz-plot:0.1.3": plot, chart

// #set page(width: auto, height: auto, margin: 1cm)
// #set text(size: 10pt)

#let rows = csv("../../../Thesis-Sean-Nachtrab-EPL-25-26/prototyping_scratchpad/gradients.csv", row-type: dictionary)
#let highlight-blue  = "Slices CA-RL-L"
#let highlight-red   = "Slices CA-RU-R"


// Colors per run (mean line / band fill)
// #let run-styles = (
//   "Run 1": (
//     line: rgb(20, 90, 180),
//     band: rgb(20, 90, 180, 45),
//   ),
//   "Run 2": (
//     line: rgb(80, 80, 80),
//     band: rgb(80, 80, 80, 45),
//   ),
// )

#let curves = (:)
#for r in rows {
  let key = r.run + "||" + r.dataset + "||" + r.axis
  let pt = (float(r.distance_from_center), float(r.grey_value))
  curves.insert(key, curves.at(key, default: ()) + (pt,))
}

// Pointwise mean / std across all curves of a run 

#let stats-for(run) = {
  // Collect y-values at each integer x across all curves of this run.
  let by-x = (:)
  for (key, pts) in curves {
    if not key.starts-with(run + "||") { continue }
    for p in pts {
      let xk = str(int(p.at(0)))
      by-x.insert(xk, by-x.at(xk, default: ()) + (p.at(1),))
    }
  }
  let xs = by-x.keys().map(int).sorted()
  let mean-pts = ()
  let lo-pts = ()
  let hi-pts = ()
  for x in xs {
    let ys = by-x.at(str(x))
    let n = ys.len()
    let m = ys.fold(0.0, (a, b) => a + b) / n
    let var = ys.fold(0.0, (a, b) => a + (b - m) * (b - m)) / n
    let sd = calc.sqrt(var)
    mean-pts.push((x, m))
    lo-pts.push((x, m - sd))
    hi-pts.push((x, m + sd))
  }
  // closed polygon for the band: lo forward + hi reversed
  (mean: mean-pts, band: lo-pts + hi-pts.rev())
}

#let highlight-curve(dataset) = {
  let combined = (:)  // x -> array of y
  for (key, pts) in curves {
    let parts = key.split("||")
    if parts.at(1) != dataset { continue }
    for p in pts {
      let xk = str(int(p.at(0)))
      combined.insert(xk, combined.at(xk, default: ()) + (p.at(1),))
    }
  }
  let xs = combined.keys().map(int).sorted()
  xs.map(x => {
    let ys = combined.at(str(x))
    let m = ys.fold(0.0, (a, b) => a + b) / ys.len()
    (x, m)
  })
}

// ---- Plot ----------------------------------------------------------------

#let chart = cetz.canvas({
  // let r1 = stats-for("Run 1")
  // let r2 = stats-for("Run 2")
  let line-blue = highlight-curve(highlight-blue)
  let line-red  = highlight-curve(highlight-red)
  cetz.draw.set-style(axes: (
  label: (offset: 0.9, anchor: "north"),
  tick: (label: (offset: 0.4)),
))

  plot.plot(
    size: (12, 6),
    x-label: [distance from center (px)],
    // x-label-anchor: "north",
    // x-label-offset: 0.5,
    y-label: [grey value],
    y-min: 0, y-max: 255,
    x-min: -800, x-max: 800,
    x-grid: true, y-grid: true,
    y-tick-step: 64,
    legend: "inner-north-east",
    legend-style: (stroke: 0.5pt + gray, padding: 0.4em, offset: (-10pt, -34pt)),
    {

      // // Run 1 band + mean
      // plot.add(
      //   r1.band, fill: true, fill-type: "shape",
      //   style: (stroke: none, fill: run-styles.at("Run 1").band),
      //   mark: none,
      // )
      // plot.add(
      //   r1.mean,
      //   style: (stroke: (paint: run-styles.at("Run 1").line, thickness: 1.2pt)),
      //   mark: none, label: [Run 1 (mean ± σ)],
      // )

      // // Run 2 band + mean
      // plot.add(
      //   r2.band, fill: true, fill-type: "shape",
      //   style: (stroke: none, fill: run-styles.at("Run 2").band),
      //   mark: none,
      // )
      // plot.add(
      //   r2.mean,
      //   style: (stroke: (paint: run-styles.at("Run 2").line, thickness: 1.2pt)),
      //   mark: none, label: [Run 2 (mean ± σ)],
      // )

      // Highlighted dataset 1: solid blue
      plot.add(
        line-blue,
        style: (stroke: (paint: rgb(0, 80, 220), thickness: 1.2pt)),
        mark: none, label: "2. CA-RL-L - Unreliable",// [#highlight-blue],
      )

      // Highlighted dataset 2: dashed red
      plot.add(
        line-red,
        style: (stroke: (
          paint: rgb(220, 40, 40),
          thickness: 1.2pt,
          dash: "dashed",
        )),
        mark: none, label: "1. CA-RU-R - Reliable",//[#highlight-red],
      )
    },
  )
})

// ---- Page layout ---------------------------------------------------------

// #align(center)[
//   #text(size: 14pt, weight: "bold")[Pixel intensity across image centers]
// ]

// #v(0.4em)

// #align(center)[
//   #text(size: 9pt, fill: gray)[
//     Mean ± 1σ across all datasets and both X/Y profiles, per run.
//   ]
// ]

// #v(1em)

// #align(center, chart)
#chart