// Segmentation methods taxonomy diagram
// Generated by Claude Opus 4.7 with custom data, approximated
// The values are not intended to be absolute

#import "@preview/cetz:0.5.0"
#import "@preview/cetz-plot:0.1.3": plot, chart

#figure(
  cetz.canvas({
    import cetz.draw: *

    // ----- Axes -----
    let ax-min = 0
    let ax-max = 10

    // X-axis
    line(
      (ax-min, 0),
      (ax-max + 0.5, 0),
      mark: (end: "stealth"),
      stroke: black + 0.8pt,
    )
    // Y-axis
    line(
      (0, ax-min),
      (0, ax-max + 0.5),
      mark: (end: "stealth"),
      stroke: black + 0.8pt,
    )

    // Axis labels
    content(
      (ax-max + 0.1, -0.7),
      anchor: "north-east",
      text(size: 11pt)[Data need (training annotations)],
    )
    content(
      (-1.3, ax-max),
      anchor: "north-east",
      angle: 90deg,
      text(size: 11pt)[Topological awareness],
    )

    // Axis endpoint annotations
    content(
      (ax-max, -0.2),
      anchor: "north",
      text(size: 8pt, fill: gray.darken(20%))[high],
    )
    content(
      (0.2, -0.2),
      anchor: "north-west",
      text(size: 8pt, fill: gray.darken(20%))[low],
    )
    content(
      (-0.2, ax-max),
      anchor: "east",
      text(size: 8pt, fill: gray.darken(20%))[high],
    )
    content(
      (-0.2, 0.3),
      anchor: "east",
      text(size: 8pt, fill: gray.darken(20%))[low],
    )

    // ----- Quadrant background tints (optional, very subtle) -----
    // These help the four quadrants register visually without
    // dominating. Comment out the four `rect` calls below to disable.
    let mid = ax-max / 2
    let tint = (
      bottom-left:  rgb("#f7f7f7"),  // low data, low topology
      bottom-right: rgb("#f0f0f0"),  // high data, low topology
      top-left:     rgb("#f0f0f0"),  // low data, high topology
      top-right:    rgb("#e8e8e8"),  // high data, high topology
    )
    rect((0, 0),     (mid, mid),         stroke: none, fill: tint.bottom-left)
    rect((mid, 0),   (ax-max, mid),      stroke: none, fill: tint.bottom-right)
    rect((0, mid),   (mid, ax-max),      stroke: none, fill: tint.top-left)
    rect((mid, mid), (ax-max, ax-max),   stroke: none, fill: tint.top-right)

    // Re-draw axes on top of the tinted quadrants
    line(
      (ax-min, 0),
      (ax-max + 0.5, 0),
      mark: (end: "stealth"),
      stroke: black + 0.8pt,
    )
    line(
      (0, ax-min),
      (0, ax-max + 0.5),
      mark: (end: "stealth"),
      stroke: black + 0.8pt,
    )

    // ----- Quadrant labels (corners, light text) -----
    content(
      (mid / 2, ax-max - 0.3),
      anchor: "north",
      text(size: 8pt, fill: gray.darken(80%), style: "italic")[
        topology-aware\
        classical
      ],
    )
    content(
      (mid + mid / 2, ax-max - 0.3),
      anchor: "north",
      text(size: 8pt, fill: gray.darken(80%), style: "italic")[
        topology-aware\
        learned
      ],
    )
    content(
      (mid / 2, mid - 0.3),
      anchor: "north",
      text(size: 8pt, fill: gray.darken(80%), style: "italic")[
        intensity-only\
        classical
      ],
    )
    content(
      (mid + mid / 2, mid - 0.3),
      anchor: "north",
      text(size: 8pt, fill: gray.darken(80%), style: "italic")[
        voxel-wise\
        learned
      ],
    )

    // ----- Method points -----
    // Each entry: (x, y, label, label-anchor)
    // label-anchor places the text relative to the dot.
    let methods = (
      (0.4, 0.4, "Otsu",                "north"),
      (1.0, 1.5, "Region-growing",      "east"),
      (1.2, 4.95, "Frangi",              "north"),
      (1.8, 6.0, "Minimal-path",        "north"),
      (8.0, 2.2, "U-Net / V-Net",       "north"),
      (6.0, 4.0, "Hybrid Frangi + U-Net", "south"),
      // (8.0, 8.0, "clDice",              "north"),
      (2.5, 7.5, "This work: Bootstrapped hybrid",              "north"),
    )

    for m in methods {
      let (x, y, label, anc) = m
      // Dot
      circle(
        (x, y),
        radius: 0.12,
        fill: black,
        stroke: none,
      )
      // Label with a small offset away from the dot
      let dx = if anc.contains("east") { 2.2 }
               else if anc.contains("west") { -0.5 }
               else { 0 }
      let dy = if anc.contains("north") { 0.45 }
               else if anc.contains("south") { -0.5 }
               else { 0 }
      content(
        (x + dx, y + dy),
        anchor: anc,
        text(size: 8.5pt)[#label],
      )
    }

    // ----- Optional: highlight your own contribution -----
    // Uncomment to mark a specific point as "this thesis":
    //
    // let thesis-x = 5.5
    // let thesis-y = 5.5
    // circle(
    //   (thesis-x, thesis-y),
    //   radius: 0.22,
    //   fill: rgb("#00bfff"),
    //   stroke: rgb("#002366") + 1pt,
    // )
    // content(
    //   (thesis-x + 0.3, thesis-y + 0.3),
    //   anchor: "south-west",
    //   text(size: 8.5pt, weight: "bold", fill: rgb("#002366"))[This thesis],
    // )
  }),
  caption: [
    Vascular segmentation methods. *x-axis:* input training-data needed. *y-axis:* level of encoding of vessel topology. Classical methods cluster on the left, requiring no training data and some hyperparameters, and vary in the priors they encode: Otsu encodes none, Frangi encodes local tubularity but not connectivity, minimal-path methods enforce connectivity by construction at the cost of user-provided seeds. Data-driven methods (U-Net, V-Net) cluster on the right with high data needs and lack topological awareness when trained with voxel-wise losses. _Hybrid approaches_, as in this thesis, combine image intensity derived vesselness (topological awareness) with two forms of user input: annotation points and adjustable hyperparameters (data needs).
  ],
) <fig:segmentation-taxonomy>

// ; topology-aware losses such as clDice raise the latter without reducing the former.