= Challenges and ablation study <ablation_study>



// REFRAME THE ABLATION STUDY AS A REACTION TO THE PERFORMANCE CHALLENGES








== Performance challenges <performance_and_memory>

// TODO: add source https://discourse.slicer.org/t/title-slow-and-unstable-performance/4988
As noted in @data_intro, the total data required for an uncompressed scan can reach into the tens or hundreds of GB if the image size is large, proving to be a unique challenge. During the initial software evaluation, 3D Slicer was successful in loading all datasets on the development machine - however it was not verified at the time how much memory was being used. This turned out to be a problem: the larger datasets resulted in un-manageable RAM utilization when trying to run un-optimized algorithms. As mentioned in section @ablation_study, the initial multi stage plugin was running into a performance wall: when implementing a 3D Slicer plugin in python, a single thread is available, and this thread locks all other 3D Slicer activity (this fact extends to 3D Slicer functions such as loading and saving, too). When running on a large scan, combined with the generation of probability maps and the sequential algorithms, memory usage exceeded ram, reached into swap, and could run seemingly indefinitely (success was only observed on smaller scans). This is a known issue for 3D Slicer [TODO SOURCE].

Methods exist to handle such large datasets: the most basic approach is cutting down of full scans into smaller chunks or subsamling the scans, however cutting scans down has the disadvantage of requiring stitching after running algorithms, and subsampling requires the the target structures to be large enough to allow it. An experiment was run, where a target scan was cut into 4 smaller sections using python. This proved to be unwieldly for annotation and running the pipeline.

// TODO: source https://www.dask.org/
Industry standard methods exist for handling large datasets: HDF5 is intended to _store_ such large multidimensional arrays and efficiently enable loading subsections, however this data storage format is totally incompatible with most medical imaging software, and is not the standard used by CT machines. Standards such as DICOM did not provision for the possibility that data such as those generated by micro-CT may exist in the future in the medical domain. 

To _operate on_ large multidimensional arrays in Python, there exist libraries such as Dask that enable "chunking" of the data to process smaller areas: this could enable improved scaling to larger scans


#figure(
  grid(
    columns: 2,
    gutter: 3pt,
    image("../../resources/misc/RAM_cpu_use_during_a_run.png"),
    image("../../resources/misc/RAM-cb-luru-r.png"),
  ),
  caption: [RAM utilization during segmentation: 1. baseline after loading dataset, bellow 24GB utilization, during processing 100% RAM and swap are used, 2. RAM utilization when loading the largest compressed scan showing full RAM and SWAP utilization: Run 1, CB-LURU-R],
)


These performance concerns highlight a continuous issue encountered during the writing of this thesis: the complexity of methods able to be tested was limited by the choice of software, volume of data and the hardware available. Lab computers available to students have 32GB of ram, less than the computer used for the testing and writing of code, and it was noted by previous students working on MicroCT imaging that they had struggled to run algorithms across the whole image. In the end, much effort was invested in the research, testing and optimization of the algorithms, and runtime concerns pushed development towards the use of methods implemented in C++ available with Python bindings, such as the SimpleITK Frangi filter used. 






== Micro-CT Challenges

// TODO: Insert image of the provided folder/data? 
These software are used in the context of analysis of CT data: users receive data from the CT machine in the form of a collection of 16 bit TIFF files: heavy, with a single 2000x2300 slice weighing *9.2MB*, and a whole 2400 slice scan weighing in at *22.1GB*, they are then windowed to 8 bit, often BMP images, and the empty slices are removed: this results in approximately a halving in total data amount. This windowing process was documented as being unprincipled: the window was chosen based on the researchers best judgment, and the original data discarded.

Furthermore, certain researchers would then compress the data in the form of JPEG image slices, as was the case with the data used in this thesis: the scans provided ranged from *0.103* to *13.2GB* (597x698x854 to 3000x3000x2653) and the original lossless data was not preserved, in both cases the windowing and the compression were motivated by data storage cost concerns. A full, uncompressed, 8 bit per pixel 3000x3000x2653 scan would occupy 217GB, a problem which is revisited in @performance_and_memory. All dataset sizes are visible in annex @uncompressed_dataset_size.

Finally, the provided data was generally given with little or no context: the data was provided in the form of a folder containing images as well as experiments that were run, with no associated dates and without grounding context such as the scan voxel size or parameters of the scanning machine.









== Ablation study

Following the positive outputs of the pipeline, an ablation study was carried out: it is common for software approaches comprising multiple steps to not correctly quantify the contribution of each individual step to the overall algorithm performance. To do so, the weight of the probability map of each step was set to 0 except one, which showed that the Frangi vesselness step was the most important to obtaining high vessel extraction performance, offering the same 26/27 performance as the full pipeline. The pipeline was also tested by disabling inference for unused steps, substantially lowering the memory and processing time footprints. Additionally the performance evaluation method was highlighted as lacking: false positives and discontinuities in the blood vessels were not properly penalized, and small vessels were not being correctly segmented; all things that point wise annotations fail to capture.

=== Outputs of the ablation study

The removal of all steps (shell removal, random forest) except vesselness resulted in improved performance for extraction of vessels in the outer shell, as noted previously being crucial, as well as a large performance increase: vessel extraction went from taking multiple hours to under 20 minutes. It also successfully reduced RAM and swap usage, enabling effective running of the algorithm on larger samples. As a result of this small ablation study, the probability map approach was simplified to reduce memory usage, with a single map being succecively updated, and focus was moved towards the use of simple, scientifically grounded extracton based on line-like features with a step for combatting the disconnections in vessels.

